### ISSUE TITLE
Error in LearningPHP/models/articles.php

### ISSUE THREAD

**Issue by DmitriyPrylutskyi** [imyourdream/LearningPHP#1]
LearningPHP/models/articles.php: Error in 83 and 99 row, **$result**

**Comment by imyourdream** [comment]
В связи с тем, что проект учебный и размещен в ознакомительных целях - wontfix
А вообще его работоспособность подтверждена многими участниками курса и последние пол года он доступен по адресу http://lizkiss.ru/
