### ISSUE TITLE
Error in LearningPHP/views/article_admin.php

### ISSUE THREAD

**Issue by DmitriyPrylutskyi** [imyourdream/LearningPHP#2]
Error in LearningPHP/views/article_admin.php in 22 row should be written
`<form method="post" action="index.php?action=<?=$_GET['action']?>&id=<?=(isset($_GET['id'])) ? $_GET['id'] : null?>">`

**Comment by imyourdream** [comment]
https://github.com/imyourdream/LearningPHP/issues/1#issuecomment-274720815
